import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";

import Layout from "@/components/Layout";
import Image from "next/image";

import ProfilePicture from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout>
          <div className="flex items-center justify-center w-full">
            {/* <div className="w-1/2">
              <Image
                src={ProfilePicture}
                alt="deveshlashkari"
                className="w-full h-auto"
              />
            </div> */}
            <div className="flex flex-col items-center self-center">
              <AnimatedText text="Devesh Lashkari" />
              <p className="my-8 text-2xl font-medium ">
                Developer | Gamer | Traveller
              </p>
              <div className="flex items-center self-center mt-2 py-15">
                <Link
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                  href="/dummy.pdf"
                  target="_blank"
                >
                  Resume
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
